### ISSUE TITLE
Non-random role assignment (Traitor/Innocent)

### ISSUE THREAD

**Issue by lydiakienbaum** [janattig/Trouble-In-MC-Town#1]
Several play-tests show that the role assignment does not seem to be completely random - it may depend on the positions where the players starting.

**Comment by janattig** [comment]
Seems like this is due to minecraft not being completely random.
Traitor assignment is carried out by the command
```mcfunction
tag @a[sort=random, limit=1] add ttt_become_traitor
```
in [this](https://github.com/janattig/Trouble-In-MC-Town/blob/main/TroubleInMCTown/data/trouble_in_mc_town/functions/utility/find_traitor.mcfunction) file, which apparently is not acting completely random.

I believe the solution is implementing a "real" pseudo random number generator (like implemented into [`ProceduralDungeons`](https://github.com/janattig/Procedural-Dungeons), specifically in the namespace [`pd_math`](https://github.com/janattig/Procedural-Dungeons/tree/main/ProceduralDungeons/data/pd_math)).

I will look into this.

EDIT: just to clarify: the roles are still not obvious before the round. Just if there are a lot of consecutive rounds, it seems like the same distribution of Traitors reoccurs after people are teleported back to their starting positions and start a new round.

**Comment by janattig** [comment]
I implemented commit 1aa1eee which potentially solves this problem. It implements a complete LCG into Trouble in MC Town which is used to assign roles.

Further playtesting might be needed to progress and close this issue

**Comment by janattig** [comment]
Playtesting reveals that this issue is most likely resolved. Traitors now really seem to be assigned randomly.
